### ISSUE TITLE
Debug vs Release

### ISSUE THREAD

**Issue by fdncred** [Phreak87/LeptonicaSharp#14]
I like to use the Debug version of Leptonica so I can step into the native C code. Can we change this in the Natives.vb file?
```vb
#If DEBUG Then
    Const DllPath As String = "leptonica-1.77.0d.dll"
#Else
    Const DllPath As String = "leptonica-1.77.0.dll"
#End If
```
That decision may have implications that you do not want when it comes to Nuget. But I'm always changing this in your code.

**Comment by Phreak87** [comment]
Changes are made. Defaulted in the next release.
Debug-library can be found in your old comment here: https://github.com/Phreak87/LeptonicaSharp/issues/2

Additionally Todo: Fix dll-loader for nuget and point nuget-version
always to the default library.
