### ISSUE TITLE
Leptonica CHM

### ISSUE THREAD

**Issue by fdncred** [Phreak87/LeptonicaSharp#15]
I created this the other day from the 1.77.0 source. I thought you'd like it.
[Leptonica.zip](https://github.com/Phreak87/LeptonicaSharp/files/2421526/Leptonica.zip)
Darren

**Comment by Phreak87** [comment]
great!

included in \help

**Comment by fdncred** [comment]
This one was generated with "All" options enabled.
[Leptonica-1.77.0pre.zip](https://github.com/Phreak87/LeptonicaSharp/files/2424189/Leptonica-1.77.0pre.zip)

**Comment by Phreak87** [comment]
Updated 1.76.1 to 1.77.0_PRE
Thank you

**Comment by fdncred** [comment]
This is from the 10-23 build. I've changed the CHM a bit. It now has a time date stamp on the bottom of the pages. It also now includes the source code from the prog folder for reference.
[Leptonica.zip](https://github.com/Phreak87/LeptonicaSharp/files/2516440/Leptonica.zip)
