### ISSUE TITLE
Testdll?

### ISSUE THREAD

**Issue by fdncred** [Phreak87/LeptonicaSharp#17]
Can you name the library something other than testdll in the assembly solution?

**Comment by Phreak87** [comment]
Fixed

**Comment by fdncred** [comment]
Just a tip. It's helpful to commit when you fix things like bb5646688a6a053c59fad3107ad9cec3a8e8bb4a
[Reference](https://help.github.com/articles/autolinked-references-and-urls/)

**Comment by Phreak87** [comment]
Hey Darren,

New version is up.

Darren Schroeder <notifications@github.com> schrieb am Fr., 28. Sep. 2018,
22:45:
