### ISSUE TITLE
Leptonica 1.77.0 static binaries

### ISSUE THREAD

**Issue by fdncred** [Phreak87/LeptonicaSharp#2]
Attached are Leptonica binaries for Windows x86 and x64 in release and debug that are compiled statically. So you don't need all the cppan.blah.blah.dll files.  This is what I'm using with tvcosine's version.

[Leptonica-1.77.0-x86_x64.zip](https://github.com/Phreak87/LeptonicaSharp/files/2388663/Leptonica-1.77.0-x86_x64.zip)

**Comment by Phreak87** [comment]
Thank you, 

i will test it as soon as possible. can you provide a documentation
how to generate this static version in a few simple steps to update
the documentation page too.

**Comment by fdncred** [comment]
From my experience, there's nothing simple about getting Leptonica built the first time, especially for people who aren't familiar with cmake and cppan.  These are my general rules for all cmake/cppan projects.

**Prerequisit Tools**

[cppan.exe](https://github.com/cppan/cppan/releases)

[cmake/cmake-gui](https://cmake.org/download/)

**Build Leptonica (partially taken from [here](http://www.leptonica.com/source/README.html))**

1. Put cppan.exe client in your path.
2. Run cppan.exe --help. This will create %userprofile%\\.cppan
3. Modify cppan.yml and point storage_dir to where you want your cppan dependencies
4. cd leptonica
5. Run ccpan.exe
6. Run cmake-gui here
7. Update the CMAKE_INSTALL_PREFIX with your install path. I usually put it under the build folder.
8. set CPPAN_BUILD_SHARED_LIBS=0 - This makes leptonica link statically so you don't have extra cppan dlls.
9. set CPPAN_USE_CACHE=0
10. Run configure several times updating cmake entries as necessary, until there are no more red entries. Then click generate to get vcxproj and sln files.
11. Open sln in Visual Studio from build dir to compile "ALL_BUILD" project for Debug and Release.
12. Build "Install" project for Debug and Release.
13. If you did everything "right" you will end up with an install folder that has a bin folder with leptonica release and debug dlls. As well as debug and release lib files in the lib folder.

**Comment by Phreak87** [comment]
Please contact meine via Facebook or Mail to discuss About collaberation

**Comment by Phreak87** [comment]
Implemented static Version

**Comment by fdncred** [comment]
[Leptonica-0926.zip](https://github.com/Phreak87/LeptonicaSharp/files/2424175/Leptonica-0926.zip)

**Comment by Phreak87** [comment]
Hi Darren,

i´ve just Updated the Librarys to our newest Version. In between the
oroginal source has
changed too. can you send me your src folder on which your library is based
on the be clear
this time. i include this in a zip-file in github too, to allow others do
the same debug with the
correct sources.

Thanks!

Am Do., 27. Sep. 2018 um 15:07 Uhr schrieb Darren Schroeder <
notifications@github.com>:

**Comment by fdncred** [comment]
I've already sent you my source code folder to compile leptonica. Do a git
pull on the source and recompile it.

**Comment by Phreak87** [comment]
Sure, thats right.

im not shure if that is the exact version of the last dll. leptonica source changes 
nearly each 2 days. my compiler has problems to compile your source folder 
(VS 2010). 
Great Changes are coming ;)

**Comment by fdncred** [comment]
[Leptonica-static.20181023.zip](https://github.com/Phreak87/LeptonicaSharp/files/2507853/Leptonica-static.20181023.zip)
Just recompiled and thought I'd share.

**Comment by Phreak87** [comment]
Great work!

i will upload it.

Am Di., 23. Okt. 2018 um 22:17 Uhr schrieb Darren Schroeder <
notifications@github.com>:

**Comment by fdncred** [comment]
[Leptonica-static-20181203.zip](https://github.com/Phreak87/LeptonicaSharp/files/2640357/Leptonica-static-20181203.zip)

**Comment by Phreak87** [comment]
Thx,



Am Mo., 3. Dez. 2018 um 17:51 Uhr schrieb Darren Schroeder <
notifications@github.com>:

**Comment by fdncred** [comment]
[liblept.zip](https://github.com/Phreak87/LeptonicaSharp/files/2980134/liblept.zip)
I'm using a new builder now for leptonica. This zip file is 7z so you'll need 7-zip to decompress it.

**Comment by Phreak87** [comment]
Great, thx!

**Comment by Phreak87** [comment]
pixReadJp2k with the new Library doesn´t work. 
So i switched back to the old 1.77 Version.
Can you please double check whats missing in the new library?

Thx!

**Comment by fdncred** [comment]
Try this one. It should have libwebp, libgif, and libjp2k included now.  Same deal - it's 7zip with zip extension.
[liblept.zip](https://github.com/Phreak87/LeptonicaSharp/files/2993032/liblept.zip)

**Comment by Phreak87** [comment]
Thx, i will give it a try.

**Comment by fdncred** [comment]
I think that one is messed up too. Looking into it now.

**Comment by fdncred** [comment]
I have it working for x64 but not x86. Let me know if you want the 64-bit one.

**Comment by Phreak87** [comment]
I want the x86 one please

Darren Schroeder <notifications@github.com> schrieb am Fr., 22. März 2019,
17:28:

**Comment by fdncred** [comment]
[liblept.zip](https://github.com/Phreak87/LeptonicaSharp/files/3008394/liblept.zip)
I tested x86 with this code and my leptonica.net and it works.
```cs
        private void JP2Text(Pix pixs)
        {
            var r1 = Jpk2IO.pixWriteJp2k("testjp2.jp2", pixs, 34, 5, PdfFormattedEncodingTypes.L_JP2K_ENCODE, 1);
        }
```

**Comment by Phreak87** [comment]
Thx! 

i will give it a try! i hope it works!

**Comment by Phreak87** [comment]
Now j2k compression works. But in my case i have lower quality with 
larger filesize :( my meaning was to save filesize to compress pdf files.
other online converters to jp2 have the same results (e.g. Amoris.jpg grows
from 250 kb to 750 kb)

anyway - you have done a great job!
