### ISSUE TITLE
Out Parameters

### ISSUE THREAD

**Issue by fdncred** [Phreak87/LeptonicaSharp#23]
While trying to use your library for a CSharp app, I notice that I need out parameters instead of just refs.  Can you add the out attribute to all out parameters?
Before:
```vb
    Public Shared Function pixGetRegionsBinary(
                ByVal pixs As Pix,
                ByRef ppixhm As Pix,
                ByRef ppixtm As Pix,
                ByRef ppixtb As Pix,
                ByVal pixadb As Pixa) As Integer
```
After
```vb
    Public Shared Function pixGetRegionsBinary(
                ByVal pixs As Pix,
                <Out()> ByRef ppixhm As Pix,
                <Out()> ByRef ppixtm As Pix,
                <Out()> ByRef ppixtb As Pix,
                ByVal pixadb As Pixa) As Integer
```
This enables a CSharp user to do that following:
```cs
static void Main(string[] args)
{
    Natives.Initialize();
    _AllFunctions.setLeptDebugOK(1);
    var pix = new Pix(file6);
    var pixa = _AllFunctions.pixaCreate(0);
    _AllFunctions.pixGetRegionsBinary(pix, out Pix ppixhm, out Pix ppixtm, out Pix ppixtb, pixa);
}
```

**Comment by Phreak87** [comment]
That's new to me. Give it a try!

**Comment by fdncred** [comment]
I tried it and it works.

**Comment by Phreak87** [comment]
I have nothing changed until now 😉. Please give me a understanding example how to work without this
Parameter

**Comment by Phreak87** [comment]
Implemented in the next release

**Comment by Phreak87** [comment]
Please check if it works in your environment

**Comment by fdncred** [comment]
The one function that I tested with, posted in this thread above, does not have Out variables. I only see three functions that have out variables. So, I wouldn't say it's implemented. Reopening.

**Comment by Phreak87** [comment]
oh crap!

now its on your function too 👍
But still Not usable in My Dev. Environment. 😐

**Comment by fdncred** [comment]
Why are you closing this issue if the problem isn't fixed?

**Comment by Phreak87** [comment]
It's fixed but not public. You have to wait
For the new version

**Comment by fdncred** [comment]
```<Out()>``` and ```<para/>``` seem to be working.
