### ISSUE TITLE
Auto Generation?

### ISSUE THREAD

**Issue by fdncred** [Phreak87/LeptonicaSharp#3]
Did you use a program to generate your source code?  If so, could you share that as well?

Thanks,
Darren

**Comment by Phreak87** [comment]
Hi Darren,

your right, i use a tool to create this library. With the NClang.Net Library
i parse the C-Source Code and then generate this Wrapper.
At the Moment the generation tool is in development too and has a few bugs and
is far away from beeing released. In the Future i will release it too. 

If you Like to work with me on this Library i can share it with you

**Comment by fdncred** [comment]
Sure. I'd like to take a look at it specifically for Leptonica.
