### ISSUE TITLE
Test Images

### ISSUE THREAD

**Issue by fdncred** [Phreak87/LeptonicaSharp#34]
It would be good to have a folder of Leptonica's test images included with your project.

**Comment by Phreak87** [comment]
You have also rights to publish. 
Please include it (and additionally the licence) and close this issues if done

**Comment by Phreak87** [comment]
Done!

**Comment by fdncred** [comment]
The images are committed? I don't see them.

**Comment by Phreak87** [comment]
Press F5 And Look into the testapplication

**Comment by fdncred** [comment]
I see them now, under testapplication/debug/images. I never would've expected them there. You and I think very differently about things. That much is clear.

**Comment by Phreak87** [comment]
Thats right.

Images are for Testing, Not for the library.
Different thinking ist good to to get the best
Of 2 Worlds. Thats often hard but delivers good
Results

Darren Schroeder <notifications@github.com> schrieb am Mi., 3. Okt. 2018,
21:07:

**Comment by fdncred** [comment]
But not in the Debug folder.  Anything under ./bin or ./obj is free to delete.  Not to mention that now my TestAppCSharp now has to learn how to traverse to your VB Test app folder.  The images should be at the same level as LeptonicaSharp, TestApplication, and TestAppCSharp (which I haven't committed yet).

**Comment by Phreak87** [comment]
In this Case thats ok.
Please Provide the c# Version in the Alpha State.
Thats helps me to understand e.g. the Out Parameter.
Comments are Working now?


Darren Schroeder <notifications@github.com> schrieb am Mi., 3. Okt. 2018,
21:18:

**Comment by Phreak87** [comment]
Moved to Testimages in the mainfolder
