### ISSUE TITLE
x86 and x64

### ISSUE THREAD

**Issue by fdncred** [Phreak87/LeptonicaSharp#35]
Add x86, x64, AnyCPU for all projects and assembly.

**Comment by Phreak87** [comment]
i like to develop explicit x86 / Debug!
you are free to compile for your needs! 
but do not commit such changes.
Projects should be all .Net 4.0. Your last commit makes
problems in all stages. Library copy functions, Nuget, VS-
Dependecies, Debugging and Github. i like to work on the
code not on such problems.

**Comment by fdncred** [comment]
With > 30 years of development experience I'm just trying to guide you down the right path. I like to work with people that are respectful and not rude and insulting. So, it sounds like neither of us are getting what we want. Good luck.
