### ISSUE TITLE
Make a debugger visualizer for pix and bitmap (esp Vs 2010)

### ISSUE THREAD

**Issue by Phreak87** [Phreak87/LeptonicaSharp#37]

**Comment by fdncred** [comment]
I wrote this [debugger visualizer](https://github.com/accord-net/framework/tree/1b27ff92a00135540c74c69f259bc5df8af84847/Tools/DebuggerVisualizers) but I have no idea if it works for 2010. I use it everyday in 2017.

I based it on this [one ](https://github.com/Jaex/ImageVisualizer)from Jaex.

This [one ](https://github.com/aberus/ImageVisualizer)has VB but they just removed 2010 support. However, you may be able to look at the last one that supports 2010 to learn.

**Comment by Phreak87** [comment]
Thx,

i wrote them today for only bitmap. more to coming.
i hope we can include Pix in the Visualizer. Great Examples
are always welcome. Maybe the provided Visualizer wont work
in VS 2015. 
by the way ... VS2015 ... the Library is .Net 4.0! please change your
Projects to this Version. Files with Version > 4 doesnt work for me and
will be deleted. (Your C# Project)
