### ISSUE TITLE
Extend and adapt to work with accordnet framework

### ISSUE THREAD

**Issue by Phreak87** [Phreak87/LeptonicaSharp#39]
including comment here:

https://github.com/accord-net/framework/issues/1585

**Comment by fdncred** [comment]
Hey Markus,
Help me understand what you mean by extend and adapt with Accord. I'm a maintainer with Accord. Cesar is the owner but he's been MIA for months.
Darren

**Comment by Phreak87** [comment]
Hey Darren,

Nice to hear from you.
My idea was to implement a namespace leptonica. And adapt naming and
conventions to accordnet. Convention means apply and applyinplace and so
on. Maybe replace pix with bitmap and convert each call in and out.


Darren Schroeder <notifications@github.com> schrieb am Do., 11. Okt. 2018,
19:37:

**Comment by fdncred** [comment]
Feel free to push a PR to Accord and I'll review it.

**Comment by Phreak87** [comment]
closed until i have a c# library to provide.
