### ISSUE TITLE
IsNothing(Values) in Structures.vb

### ISSUE THREAD

**Issue by fdncred** [Phreak87/LeptonicaSharp#4]
I think something went wrong here.
https://github.com/Phreak87/LeptonicaSharp/blob/60a1585c78f3548b0cfa26db9d6c343f87144724/LeptonicaSharp/Structures.vb#L28

Lowercase isnothing(values) is all over the structures.vb file. Is that what you intended? The entire line is lower case.

While we're here, I don't understand these properties. This my be because of my ignorance in VB.
```vb
ReadOnly Property start_usec as Integer
	Get
	if IsNothing(Values) Then Return Nothing
				Return Values.start_usec
		Return Nothing '<-- What's the purpose of this?
	End Get
End Property
```
Shouldn't it be something like this?
```vb
ReadOnly Property start_sec as Integer
    Get
        If IsNothing(Values) Then
            Return Nothing
        Else
	    Return Values.start_sec
        End If
    End Get
End Property

```

You also have unterminated strings on every ```#Region "IDisposable Support``` line in this file.

Darren

**Comment by Phreak87** [comment]
:) Okey,

lower and uppercase are the same in VB. so this works as expected.
the get is also correct. return nothing is never called. this is a dev.
value that means - if no return comes before this is the last exit without
getting errors - this should never occur. If i finish development this will be removed
during code cleanup.
i always try to write less lines of code. your code is better readable and works same
but in 5 lines of code. For the few variances in the wrapperbuilder i prefer less lines
to keep a better overview.
Region String Termination is missing - Fixed it
