### ISSUE TITLE
Pushing Changes

### ISSUE THREAD

**Issue by fdncred** [Phreak87/LeptonicaSharp#41]
I just tried to push some minor changes and you apparently disabled my access, which is ok with me. Your recent changes messed up the C# text project and I was just going to fix them for you.

**Comment by Phreak87** [comment]
your account is enabled again. 
but check again the All_Images folder. i moved the images in there into the folder "leptonica".
maybe you can use the new features with optional parameters at the end of a function (not moving parameters like before). Happy Uploading!

**Comment by fdncred** [comment]
Pushed changes to match your new folder changes.
