### ISSUE TITLE
Bug with 1BPP conversion

### ISSUE THREAD

**Issue by fdncred** [Phreak87/LeptonicaSharp#44]
Before:
![before](https://user-images.githubusercontent.com/343840/48079722-93cdd000-e1b1-11e8-96f0-a90791669f3d.png)
After:
![after](https://user-images.githubusercontent.com/343840/48079727-97f9ed80-e1b1-11e8-9245-f09b8219b953.png)
My code produces this with the tnv-cosine version of Leptonica.net.
![mine](https://user-images.githubusercontent.com/343840/48079762-ab0cbd80-e1b1-11e8-8780-e82893b26b3f.png)

It looks to me like all the rows are not getting written properly.

My input png, for testing:
![ca03pers](https://user-images.githubusercontent.com/343840/48079835-d55e7b00-e1b1-11e8-9761-d84c73ca85d8.png)

**Comment by Phreak87** [comment]
i found a issue in the dataStatic property.
the shown error comes from this.
Fixed it.
