### ISSUE TITLE
Leptonica Binaries location

### ISSUE THREAD

**Issue by fdncred** [Phreak87/LeptonicaSharp#46]
Would it be possible to put the leptonica binaries in a folder that isn't prone to being deleted? Perhaps something like this:
├───ALL_Help
│   └───HelpImages 
├───ALL_Images
│   └───input
│   └───Leptonica
├───CS_Lib
│   └───Properties
├───CS_Test
│   └───Properties
├───LeptLibs
│   └───x64
│   └───x86
├───VB_Lib
│   └───Extensions
│   └───Functions
│   └───HelpImages
│   └───My Project
├───VB_Test
│   └───My Project
│   └───Prog
└───VB_Viz
    └───My Project

**Comment by Phreak87** [comment]
restructured a few other folders too.
see updated structure.
