### ISSUE TITLE
Cleanup Properties

### ISSUE THREAD

**Issue by fdncred** [Phreak87/LeptonicaSharp#48]
Here's another idea. I don't like seeing duplicate properties when debugging. It is confusing.  One way to avoid that is with `<DebuggerBrowsable(DebuggerBrowsableState.Never)>` which hides properties from the debugger.
Example:
```vb
Public Class Pix
    Implements IDisposable
    Public Pointer As IntPtr
    <DebuggerBrowsable(DebuggerBrowsableState.Never)>
    Private Values As New Marshal_Pix
    Private Caching As New Dictionary(Of String, Object)
```
Now the `Values` property isn't shown during debugging and all you see are the properties you expect.
![debugging](https://user-images.githubusercontent.com/343840/48647846-d910af80-e9b2-11e8-9468-f5ceb8fb82cf.png)

**Comment by Phreak87** [comment]
good idea,

i implemented it for pointer, disposable, values and caching (background vars).
this gives a much clearer picture over the propertys -

**Comment by Phreak87** [comment]
New Version is up!

The private variables are now hidden,
the filename for write has no fileexists-check and
Void Parameters works great.

Have fun ;)



Am Fr., 16. Nov. 2018 um 22:20 Uhr schrieb Markus Eckl <nbhcrew@gmail.com>:
