### ISSUE TITLE
Converting 32bpp to Bitmap

### ISSUE THREAD

**Issue by fdncred** [Phreak87/LeptonicaSharp#51]
Your conversion using Leptonica's built in C methods remove the alpha channel when converting 32bpp.

**Comment by Phreak87** [comment]
thats right. 
maybe you can export as png / jpg or ask dan bloomberg to ensure the alpha
channel is included in the org. lib. correct in the leptonica lib is right way to fix.

**Comment by fdncred** [comment]
My code handled it fine. I'll research it a bit.

**Comment by fdncred** [comment]
The problem is in leptonica's ```pixWriteMemBmp()```. So, if we want to maintain the alpha channel, the only real choces are: 1) Get Dan to fix it, which probably won't happen, 2) Don't fix it, 3) Use something like my code that handles it properly.

Notes:
     (1) 2 bpp bmp files are not valid in the spec, and are
         written as 8 bpp.
     (2) pix with depth <= 8 bpp are written with a colormap.
         16 bpp gray and 32 bpp rgb pix are written without a colormap.
     **(3) The transparency component in an rgb pix is ignored.
         All 32 bpp pix have the bmp alpha component set to 255 (opaque).**
     (4) The bmp colormap entries, RGBA_QUAD, are the same as
         the ones used for colormaps in leptonica.  This allows
         a simple memcpy for bmp output.

**Comment by fdncred** [comment]
Fixed in be3562304ce519684b661434705905cdc8d87334
