### ISSUE TITLE
Merge Change markers in VB_TEST Module1.vb

### ISSUE THREAD

**Issue by fdncred** [Phreak87/LeptonicaSharp#52]
From what I can tell from Github history, it looks like you may have inadvertently pushed some merge change markers in module1.vb. It's not a priority to fix unless you want to compile VB_TEST. I can't tell which ones you want to keep.

**Comment by Phreak87** [comment]
I will fix...
Cache is wrong ... Should work Same as datastatic.



Am Mi., 5. Dez. 2018, 15:32 hat Darren Schroeder <notifications@github.com>
geschrieben:

**Comment by Phreak87** [comment]
can this be closed?

**Comment by fdncred** [comment]
Looks good to me.
