### ISSUE TITLE
pixSetUnderTransparency signature incorrect

### ISSUE THREAD

**Issue by fdncred** [Phreak87/LeptonicaSharp#53]
This is not correct.
```cs
public static Pix pixSetUnderTransparency(Pix pixs, uint val, DebugOnOff debug)
```
It should be:
```cs
public static Pix pixSetUnderTransparency(Pix pixs, uint val, int debug)
```

**Comment by Phreak87** [comment]
This is correct. Debug is managed by XML as a enumeration instead of int which is also 0 and 1

**Comment by fdncred** [comment]
Nope. There is no 0.
```cs
     public enum DebugOnOff
    {
        DebugOn = 1,
        DebugOff = 2
    }
```

**Comment by Phreak87** [comment]
i checked a few examples.Enum DebugOnOff is because of the BuildConfig.xml
but should have values 0 and 1 instead of 1 and 2. Fixed it.
