### ISSUE TITLE
Get rid of all the underscores

### ISSUE THREAD

**Issue by fdncred** [Phreak87/LeptonicaSharp#60]
Totally don't get naming all the functions wrong with a preceding underscore. This is exactly why Visual Studio has filters on auto-completion.
![properties](https://user-images.githubusercontent.com/343840/49942681-9eb00a80-feab-11e8-96aa-0daa8a601343.png)
![fields](https://user-images.githubusercontent.com/343840/49942698-a8d20900-feab-11e8-91ae-abe5718cafba.png)
![methods](https://user-images.githubusercontent.com/343840/49942702-acfe2680-feab-11e8-8157-33c5f099278e.png)
![extensions](https://user-images.githubusercontent.com/343840/49942706-aff91700-feab-11e8-9104-e2117aaa44eb.png)

**Comment by Phreak87** [comment]
Underscores can be removed. 
Function names should without the class name.
Think about sarray.sarrayaddstring or pixaclass.pixaadd.
Only use.add or .addstring is nice with all parameters predefined.
If you want to use the full function names _all. Function
Is always there.

**Comment by fdncred** [comment]
In general, I'm satisfied if every function name matches the exact function name in Leptonica. If everything is in the All namespace, that's fine too, because I can "using static Leptonica.All" and have visibility to every function just like I would in C/C++.

**Comment by Phreak87** [comment]
My internal view is 
[Class].[Function] (With Defaults, optionals moved to the end and source removed by the own Class).
[_All].[Function] (With Defaults, Optionals if the are on the end)
[Native].[Function] (Use Pointers instead of classes, All parameters)

**Comment by Phreak87** [comment]
This makes it possible to write own code faster with [class].[function] and
convert the C-Examples to LeptonicaSharp with the _all Class and all Parameters
including the own class.

**Comment by Phreak87** [comment]
removed underscores.
