### ISSUE TITLE
dotnet core?

### ISSUE THREAD

**Issue by fdncred** [Phreak87/LeptonicaSharp#61]
What are your thoughts on dotnet core and making leptonicasharp support it?

**Comment by Phreak87** [comment]
i have no experience with .net core. i have to work with it a little to see which
effort it takes to build on this platform

**Comment by fdncred** [comment]
The key to dotnet core is it's the fastest. It's equitable to c/c++ in terms of speed. The major benefit to most people is that it's a standard that runs on windows, linux, and mac.

I just compiled the cs_lib and cs_test on my mac.

**Comment by Phreak87** [comment]
it compiles? if this is that simple then we should provide this lib too.
... i hate MAC!
