### ISSUE TITLE
can't load nuget package in vs_2017

### ISSUE THREAD

**Issue by hedonis** [Phreak87/LeptonicaSharp#63]
When try
PM> Install-Package LeptonicaSharp -Version 1.77.0.1

I get :
Install failed. Rolling back...
Package 'leptonicaSharp.1.77.0.1' does not exist in project 'WindowsFormsApp3'
Package 'leptonicaSharp.1.77.0.1' does not exist in folder
'C:\Users\seba\source\repos\WindowsFormsApp3\packages'
Executing nuget actions took 867,98 ms
Install-Package : Could not install package 'leptonicaSharp 1.77.0.1'. You are trying to install this
package into a project that targets '.NETFramework,Version=v4.6.
1', but the package does not contain any assembly references or content files that are compatible
with that framework. For more information, contact the package autho
r.
At line:1 char:16
+ Install-Package <<<< LeptonicaSharp -Version 1.77.0.1
+ CategoryInfo : NotSpecified: (:) [Install-Package], Exception
+ FullyQualifiedErrorId :
NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

Can You help me?

**Comment by Phreak87** [comment]
You can clone the repo and build the cs lib. 
Then you get a DLL with the wrapper. Copy this DLL and the leptonica DLL from the lib_lept folder to your project and add the LeptonicaSharp as library. Please give feedback so that I can close this issue

**Comment by Phreak87** [comment]
The nuget contained library is .net 4 and outdated because of a few frequent changes last time.
But you can compile the latest on any higher level like 4.6. make sure the processor architecture is the same as in your project. If you need more help please let me know.

**Comment by hedonis** [comment]
PM> Install-Package LeptonicaSharp -Version 0.0.0 
install properly but i can't find otsu threshold or  selCreateBrick(1, 50, 0, 0, 0)

**Comment by hedonis** [comment]
Ok. I did it like You siad. It look's good. I try how it works now.

**Comment by Phreak87** [comment]
Selcreatebrick can be "new sel(...)" Or _all.selcreatebrick. for the other class functions remove the class (pix.pixdilate -> pix.dilate).
