### ISSUE TITLE
ALL_Projects.sln doesn't compile on MSVS 2017

### ISSUE THREAD

**Issue by Scatterblak** [Phreak87/LeptonicaSharp#64]
Initial load/run results in:

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1503	Argument 3: cannot convert from 'int' to 'Enumerations.L_access_storage'	{PATH}\Program.cs	397	Active

Intellisense complains about this line:
var pix1 = pixaGetPix(pixa, i, (int)Enumerations.L_access_storage.L_CLONE);

I dloaded this lib to support some image processing in a large Lucee/vb.net platform - c# isn't my specialty and I don't immediately know what the problem is.  Hopefully someone can eyeball it and suggest a quick fix? :)

--S

**Comment by fdncred** [comment]
If you upload a zip of your sample solution that produces this error I'll help you fix it. I looked at the code and I don't see the problem.

**Comment by Scatterblak** [comment]
Hi Darren,

It's not my code - it's the sample code that's included with Leptonica. If
you click 'Download' on github, open the zip, save it all to a directory,
and then open the sample solution with MSVS 2017, you get the error.

W. Sean Harrison
CTO, Principal

HaGiMo LLC
p: 615.838.9289
e: sean.harrison@hagimo.com

http://www.hagimo.com

The contents of this email message and any attachments are intended solely
for the addressee(s) and may contain confidential and/or privileged
information and may be legally protected from disclosure. If you are not
the intended recipient of this message or their agent, or if this message
has been addressed to you in error, please immediately alert the sender by
reply email and then delete this message and any attachments. If you are
not the intended recipient, you are hereby notified that any use,
dissemination, copying, or storage of this message or its attachments is
strictly prohibited.

**Comment by fdncred** [comment]
ok, i downloaded the source from the release of 1.77.0.2 and compiled it. I see the error in CS_Test that you're talking about. You need to fix it like this.

Change this:
```cs
var pix1 = pixaGetPix(pixa, i, (int)Enumerations.L_access_storage.L_CLONE);
```
To this:
```cs
var pix1 = pixaGetPix(pixa, i, Enumerations.L_access_storage.L_CLONE);
```

**Comment by Scatterblak** [comment]
Ty sir - much appreciated!
