### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by Phreak87** [Phreak87/LeptonicaSharp#7]
Extend classes with functions instead of using _allfunctuons

**Comment by Phreak87** [comment]
Maybe FDNCred like to provide a list of functions for the classes in a ordered structure. 
That means: a XML-like format with Class (e.g. Pix) => Group (e.g. Transform, Convert, ...) => FunctionName. Doing this by simply adding all pix functions pix is too much. The functions
are overloaded too, so that you need only 1 function to handle 10 functions.

**Comment by fdncred** [comment]
1. I don't read German.
2. I won't be translating vb to c#.
3. So, when you have a c# version I made consider helping. Until then I'll keep working on my own c# version.

**Comment by Phreak87** [comment]
1.) Sure, i know :) i Translated it for you in comment 2
2.) This Task is language independent (XML)
3.) maybe you have function groups in your version.
C# Version is in build. But i first fixed the issues based on your comments.

**Comment by Phreak87** [comment]
i hope you are not angry about the assign.

my intention was only to create a xml-file like this with the functions you
need for your applications:
for my application needs i do the same. like in this example.

<Class Name="PIX">
<Extend    Name="PixFromBitmap" as="Constructor"/>
<Extend    Name="PixConvert32to16" Group="Convert" as="Function"/>
</Class>

New Version is up!
(much faster Pix (Bitmap)) and Pix.Display

Am Di., 25. Sep. 2018 um 22:13 Uhr schrieb Darren Schroeder <
notifications@github.com>:

**Comment by fdncred** [comment]
I'm not angry. I just don't have much time. I'll look at your latest later this week.  I'd really like to see your generator.

**Comment by fdncred** [comment]
Help me understand what you're doing with BuildConfig.xml. I still don't understand it's use. I figure it's what this issue is all about.

**Comment by Phreak87** [comment]
I translate the comments inside the XML to my bad English 😁. And Yor right! This issue is all About this XML.
Many ideas from your Side (e.g. Extensions for Classes) are based in this XML. So if you Like a specific function or constructor i have to add 1 Line in this XML. The XML ist also in development and grows with function specific issued.

**Comment by Phreak87** [comment]
BuildConfig.xml is Updated and contains now english comments.
i hope this helps understanding. if questions come up - ask me what
this values mean.

**Comment by fdncred** [comment]
What uses this BuildConfig.xml?  Is it your nclang application or something else?

**Comment by Phreak87** [comment]
The nclang wrapper builder use this to overwrite values and extend some classes and functions.

**Comment by Phreak87** [comment]
E.g. the comment checks are in each function with this comment ...

**Comment by fdncred** [comment]
When you release the nclang wrapper builder, if that ever happens, i'll look more closely at the xml file.

**Comment by Phreak87** [comment]
No Problem, 

XML is low hanging fruits. just copy/paste. for my needs the checks  are
fine enouth. if you like to have other checks i should implement let me know.

**Comment by Phreak87** [comment]
i hope that i can publish a new version today with the most issues from
you are corrected and implemented. just a few checks to be sure. 
stay tuned

**Comment by Phreak87** [comment]
Recreate to keep that topic clean
